# Ejecutar desde la raíz del repositorio si solo quieres crear carpetas.
$folders = @(
  ".github/workflows",
  "backend/app/api/v1/routes",
  "backend/app/core",
  "backend/app/middleware",
  "backend/app/monitoring",
  "backend/app/prompts",
  "backend/app/rules",
  "backend/app/schemas",
  "backend/app/services/vision",
  "backend/app/services/llm",
  "backend/app/services/recommendation",
  "backend/app/utils",
  "backend/models",
  "backend/scripts",
  "backend/tests/unit",
  "backend/tests/integration",
  "frontend/public",
  "frontend/src/assets",
  "frontend/src/components/CameraCapture",
  "frontend/src/components/DetectionOverlay",
  "frontend/src/components/ResultPanel",
  "frontend/src/components/DetectionHistory",
  "frontend/src/features/camera",
  "frontend/src/features/detections",
  "frontend/src/hooks",
  "frontend/src/services",
  "frontend/src/types",
  "frontend/src/utils",
  "frontend/tests/unit",
  "frontend/tests/e2e",
  "infra/cloud",
  "infra/docker",
  "infra/nginx",
  "infra/scripts",
  "data/sample_images",
  "data/test_results",
  "docs/architecture/adr",
  "docs/api",
  "docs/responsible-ai",
  "docs/scrum/sprints",
  "docs/testing",
  "docs/deployment",
  "tests/e2e"
)

foreach ($folder in $folders) {
  New-Item -ItemType Directory -Force -Path $folder | Out-Null
  New-Item -ItemType File -Force -Path (Join-Path $folder ".gitkeep") | Out-Null
}
